# Generated by Django 5.1.6 on 2025-02-13 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('document', 'Document'), ('mcq', 'MCQ Quiz')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='course_files/')),
                ('text', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='course.course')),
            ],
        ),
    ]
